### ISSUE TITLE
Use can see their car

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Add a div container to the HTML with background color.
- [x] Insert car image into top left corner of the container
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors.
