### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List
- [x] Use the querySelector method to select the car from the HTML document and store it in a new variable
- [x] Add an event listener on the new variable that will listen for the keydown event
- [x] Utilize the transform property to rotate the image based on the keydown input key
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors.
