### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List
- [x] Listen for keydown events of the space character
- [x] Implement a data model that keeps track of the car's position on the page
- [x] Implement the start car functionality, utilizing the timer to create a smooth movement
- [x] Check for Errors
