### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Implement functionality for clearing interval when user enter the space character
- [x] Implement car properties for keeping track of when the car is started and stopped
- [x] Keep track of the car's status in the data model
