### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Implement a switch case in the moveCar function that moves the car based on the direction of the car
- [x] Using positionTop to account for vertical movement of the car
- [x] Test for bugs
